services:
  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./back-end
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: mydb
      DB_USER: root
      DB_PASSWORD: password
      DJANGO_SETTINGS_MODULE: djangoproject.settings
    volumes:
      - ./back-end:/app

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    user: "0:0"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
